# Nixpacks configuration for Next.js
[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x", "curl"]

[phases.build]
cmds = ["npm ci --legacy-peer-deps", "npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[phases.install]
aptPkgs = ["curl"]